name: HelloBot

on:
  schedule:
      - cron: '0 */3 * * *'

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: HelloBot
      run: |
        npm ci
        npm start
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
